name: build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      GTEST_COLOR: yes

    steps:
    - uses: actions/checkout@v4

    - name: fetch dependencies
      run: |
        sudo bash script/setup.sh
    
    - name: build and test
      run: |
        bash script/build_and_test.sh

    - name: check codestyle
      run: |
        bash script/tidy.sh


